"""sars — Species-area relationship curve fitting in Python.

Conceptual mirror of the R `sars` package (Matthews et al. 2019),
native to the Python scientific stack.
"""

from sars._inference import (
    AveragedSAR,
    BootstrappedCI,
    MultiSARFit,
    aicc,
    akaike_weights,
    bootstrap_ci,
    sar_average,
    sar_multi,
)
from sars._io import from_csv, from_geodataframe, from_pyinaturalist, load_galap
from sars._plots import plot_average, plot_fit, plot_multi, plot_residuals
from sars._models import (
    SARFit,
    sar_asymp,
    sar_betap,
    sar_chapman,
    sar_epm1,
    sar_epm2,
    sar_gompertz,
    sar_heleg,
    sar_koba,
    sar_linear,
    sar_loga,
    sar_mmf,
    sar_monod,
    sar_negexpo,
    sar_p1,
    sar_p2,
    sar_power,
    sar_powerR,
    sar_ratio,
    sar_weibull3,
    sar_weibull4,
)
from sars._threshold import ThresholdFit, sar_threshold

__all__ = [
    "AveragedSAR",
    "BootstrappedCI",
    "MultiSARFit",
    "SARFit",
    "ThresholdFit",
    "aicc",
    "akaike_weights",
    "bootstrap_ci",
    "from_csv",
    "from_geodataframe",
    "from_pyinaturalist",
    "load_galap",
    "sar_average",
    "sar_multi",
    "sar_threshold",
    "plot_average",
    "plot_fit",
    "plot_multi",
    "plot_residuals",
    "sar_asymp",
    "sar_betap",
    "sar_chapman",
    "sar_epm1",
    "sar_epm2",
    "sar_gompertz",
    "sar_heleg",
    "sar_koba",
    "sar_linear",
    "sar_loga",
    "sar_mmf",
    "sar_monod",
    "sar_negexpo",
    "sar_p1",
    "sar_p2",
    "sar_power",
    "sar_powerR",
    "sar_ratio",
    "sar_weibull3",
    "sar_weibull4",
]
